import os
import attrs
import json
import pandas as pd
from pathlib import Path

from nuremics import Process
from nuremics_labs.ops.general import projectile_model


@attrs.define
class ProjectileModelProc(Process):
    """
    Simulate the motion of a projectile and compare its trajectory with the analytical solution.

    Process
    -------
        A/ simulate_projectile_motion
            Simulate the motion of a 2D rigid body under gravity projected with an initial velocity.
        B/ calculate_analytical_trajectory
            Calculate the theoretical trajectory of a projectile using analytical equations.
        C/ compare_model_vs_analytical_trajectories
            Plot and save the comparison between simulated (model) and theoretical projectile trajectories.

    Input parameters
    ----------------
        gravity : float
            Gravitational acceleration (m/s²).
        mass : float
            Mass of the body (kg).

    Input paths
    -----------
        velocity_file : json
            File containing the velocity initial conditions {v0 (m/s); angle (°)}.
        configs_folder : folder
            'solver_config.json' : File containing the parameters for solver configuration.
            'display_config.json' : File containing the parameters for display configuration.
        coords_file : csv
            File with 2D coordinates ('X', 'Y') of the polygonal shape to simulate.

    Internal variables
    ------------------
        dict_velocity : dict
            Initial conditions loaded from velocity_file.
        dict_solver_config : dict
            Solver configuration loaded from configs_folder.
        dict_display_config : dict
            Display configuration loaded from coords_file.
        df_trajectory_model : pd.DataFrame
            DataFrame with simulated trajectory generated by the model.
        df_trajectory_model_vs_theory : pd.DataFrame
            DataFrame with analytical and simulated (model) trajectories.

    Outputs (stored in self.output_paths)
    -------
        comp_folder : folder
            'results.xlsx' : File containing simulated (model) and theoritical trajectories.
            'model_vs_theory.png' : Image comparing both trajectories.
    """

    # Parameters
    gravity: float = attrs.field(init=False, metadata={"input": True})
    mass: float = attrs.field(init=False, metadata={"input": True})
    
    # Paths
    velocity_file: Path = attrs.field(init=False, metadata={"input": True}, converter=Path)
    configs_folder: Path = attrs.field(init=False, metadata={"input": True}, converter=Path)
    coords_file: Path = attrs.field(init=False, metadata={"input": True}, converter=Path)

    # Internal
    dict_velocity: dict = attrs.field(init=False)
    dict_solver_config: dict = attrs.field(init=False)
    dict_display_config: dict = attrs.field(init=False)
    df_trajectory_model: pd.DataFrame = attrs.field(init=False)
    df_trajectory_model_vs_theory: pd.DataFrame = attrs.field(init=False)

    def __call__(self):
        super().__call__()

        self.simulate_projectile_motion()
        self.calculate_analytical_trajectory()
        self.compare_model_vs_analytical_trajectories()
    
    def simulate_projectile_motion(self):
        """
        Simulate the motion of a 2D rigid body under gravity projected with an initial velocity.

        Uses
        ----
            gravity
            mass
            velocity_file
            configs_folder/solver_config.json
            configs_folder/display_config.json
            coords_file
            dict_velocity
            dict_solver_config
            dict_display_config
        
        Modifies
        --------
            dict_velocity
            dict_solver_config
            dict_display_config
            df_trajectory_model
        """

        # Load initial conditions
        with open(self.velocity_file) as f:
            self.dict_velocity = json.load(f)

        # Load solver configuration
        path = self.configs_folder / "solver_config.json"
        with open(path) as f:
            self.dict_solver_config = json.load(f)

        # Load display configuration
        path = self.configs_folder / "display_config.json"
        with open(path) as f:
            self.dict_display_config = json.load(f)

        # Read 2D polygon shape coordinates (X, Y) from CSV file
        df_points = pd.read_csv(
            filepath_or_buffer=self.coords_file,
        )

        # Run simulation model
        self.df_trajectory_model = projectile_model.simulate_projectile_motion(
            df_points=df_points,
            mass=self.mass,
            gravity=self.gravity,
            v0=self.dict_velocity["v0"],
            angle=self.dict_velocity["angle"],
            timestep=self.dict_solver_config["timestep"],
            fps=self.dict_display_config["fps"],
            window_size=self.dict_display_config["size"],
            silent=self.silent,
        )

    def calculate_analytical_trajectory(self):
        """
        Calculate the theoretical trajectory of a projectile using analytical equations.

        Uses
        ----
            gravity
            dict_velocity
            df_trajectory_model

        Modifies
        --------
            df_trajectory_model_vs_theory

        Generates
        ---------
            comp_folder/results.xlsx
        """

        # Create output directory
        output_dir:Path = Path(self.output_paths["comp_folder"])
        output_dir.mkdir(
            exist_ok=True,
            parents=True,
        )

        # Compute analytical solution and save results to Excel
        self.df_trajectory_model_vs_theory = projectile_model.calculate_analytical_trajectory(
            df=self.df_trajectory_model,
            v0=self.dict_velocity["v0"],
            angle=self.dict_velocity["angle"],
            gravity=self.gravity,
            filename=os.path.join(self.output_paths["comp_folder"], "results.xlsx"),
        )
    
    def compare_model_vs_analytical_trajectories(self):
        """
        Plot and save the comparison between simulated (model) and theoretical projectile trajectories.

        Uses
        ----
            df_trajectory_model_vs_theory

        Generates
        ---------
            comp_folder/model_vs_theory.png
        """

        projectile_model.compare_model_vs_analytical_trajectories(
            df=self.df_trajectory_model_vs_theory,
            filename=os.path.join(self.output_paths["comp_folder"], "model_vs_theory.png"),
            silent=self.silent,
        )


if __name__ == "__main__":

    # ================================================================== #
    #                      USER-DEFINED PARAMETERS                       #
    #              >>>>> TO BE EDITED BY THE OPERATOR <<<<<              #
    # ================================================================== #

    # Working directory
    working_dir = Path(r"...")
    
    # Input parameters
    gravity = -9.81
    mass = 0.1
    
    # Input paths
    velocity_file = Path(r"...") / "velocity.json"
    configs_folder = Path(r"...") / "configs"
    coords_file = Path(r"...") / "points_coordinates.csv"

    # Output paths
    comp_folder = "comparison"

    # ================================================================== #

    # Go to working directory
    os.chdir(working_dir)

    # Create dictionary containing input data
    dict_inputs = {
        "gravity": gravity,
        "mass": mass,
        "velocity_file": velocity_file,
        "configs_folder": configs_folder,
        "coords_file": coords_file, 
    }
    
    # Create process
    process = ProjectileModelProc(
        dict_inputs=dict_inputs,
        set_inputs=True,
    )

    # Define output paths
    process.output_paths["comp_folder"] = comp_folder

    # Run process
    process()
    process.finalize()